"""Shared demo-content loader — the single source of truth for demo dashboards.

The demo workspace (queries + dashboards) is defined declaratively as JSON files
under ``backend/seed_data/demo/`` so the content lives in versioned files rather
than hardcoded Python:

  - ``queries.json`` : ``{logical_key: {name, sql, params}}``
  - ``boards.json``  : ``[{seed_id, name, starter, spec}, ...]`` where every widget
    references a query by the ``"@<logical_key>"`` placeholder (resolved to the
    real query UUID at seed time).

The DATA behind those dashboards is four deterministic datasets (17 tables,
generated by ``seed_data/generators/``) distributed as **parquet files** —
the SINGLE source for all demo data paths: parquet is written once to the
deterministic local directory ``backend/seed_data/parquet/<dataset>/<table>.parquet``
(``export_demo_parquet_local`` + ``local_parquet_datastore_config``) and served
read-only via ``read_parquet`` views.

There is NO ``duckdb`` single-file path any more — the legacy ``.duckdb`` bundle
was removed in D1.  The ``seed_data/parquet/`` files are the canonical local
offline source (Nubi does not host a writable managed lakehouse).

Two consumers share this loader:
  - ``seed.py --demo`` (superuser): materialises ALL boards.
  - ``app/sample.py`` (per project): seeds the full demo bundle on signup /
    project creation (removable; everything tagged ``sample=true``).
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from seed_data.generators import ALL_TABLES, DATASET_TABLES

_SEED_DATA_DIR = Path(__file__).resolve().parent.parent / "seed_data"
_DEMO_DIR = _SEED_DATA_DIR / "demo"

# Default local parquet export directory (gitignored, generated on demand).
LOCAL_PARQUET_DIR = _SEED_DATA_DIR / "parquet"

# Legacy alias: the retail star-schema tables (the original demo dataset).
DEMO_TABLES: tuple[str, ...] = DATASET_TABLES["retail_sales"]

# All 17 demo tables across the four datasets.
ALL_DEMO_TABLES: tuple[str, ...] = ALL_TABLES


# ---------------------------------------------------------------------------
# Demo fixture loaders
# ---------------------------------------------------------------------------


def load_queries() -> dict[str, dict[str, Any]]:
    """Return ``{logical_key: {name, sql, params}}`` from queries.json."""
    with open(_DEMO_DIR / "queries.json") as f:
        return json.load(f)


def load_boards(starter_only: bool = False) -> list[dict[str, Any]]:
    """Return board fixtures ``[{seed_id, name, starter, spec}, ...]``."""
    with open(_DEMO_DIR / "boards.json") as f:
        boards = json.load(f)
    return [b for b in boards if b.get("starter")] if starter_only else boards


def load_flows() -> list[dict[str, Any]]:
    """Return flow fixtures ``[{seed_id, name, enabled, schedule, spec}, ...]``.

    Returns empty list when flows.json is absent so older deployments don't fail.
    """
    flows_path = _DEMO_DIR / "flows.json"
    if not flows_path.exists():
        return []
    with open(flows_path) as f:
        return json.load(f)


def referenced_query_keys(boards: list[dict[str, Any]]) -> list[str]:
    """Logical query keys referenced by the given boards (via ``@key`` placeholders)."""
    keys: set[str] = set()

    def walk(node: Any) -> None:
        if isinstance(node, str):
            if node.startswith("@"):
                keys.add(node[1:])
        elif isinstance(node, dict):
            for v in node.values():
                walk(v)
        elif isinstance(node, list):
            for v in node:
                walk(v)

    for b in boards:
        walk(b["spec"])
    return sorted(keys)


def resolve_placeholders(spec: Any, idmap: dict[str, str]) -> Any:
    """Deep-copy *spec*, replacing every ``"@key"`` string with ``idmap["@key"]``.

    Unknown placeholders resolve to ``""`` (an empty query_id renders as a
    "needs configuration" widget rather than crashing).
    """
    if isinstance(spec, str):
        return idmap.get(spec, "") if spec.startswith("@") else spec
    if isinstance(spec, dict):
        return {k: resolve_placeholders(v, idmap) for k, v in spec.items()}
    if isinstance(spec, list):
        return [resolve_placeholders(v, idmap) for v in spec]
    return spec


# ---------------------------------------------------------------------------
# Local parquet export (offline / no-S3 distribution path)
# ---------------------------------------------------------------------------


def _parquet_local_path(dataset: str, table: str, base_dir: Path) -> Path:
    return base_dir / dataset / f"{table}.parquet"


def export_demo_parquet_local(
    force: bool = False,
    base_dir: str | os.PathLike | None = None,
) -> dict[str, str]:
    """Write every demo table to local parquet files; return ``{table: abs_path}``.

    Files land under ``<base_dir>/<dataset>/<table>.parquet`` (default:
    ``backend/seed_data/parquet/``).  Idempotent — existing files are kept
    unless ``force=True``; a dataset is only generated when at least one of
    its files is missing, so repeat seeds are cheap.
    """
    import pyarrow.parquet as pq  # noqa: PLC0415

    from seed_data.generators import build_dataset  # noqa: PLC0415

    base = Path(base_dir) if base_dir is not None else LOCAL_PARQUET_DIR
    paths: dict[str, str] = {}
    for dataset, tables in DATASET_TABLES.items():
        targets = {t: _parquet_local_path(dataset, t, base) for t in tables}
        if force or not all(p.exists() for p in targets.values()):
            built = build_dataset(dataset)
            (base / dataset).mkdir(parents=True, exist_ok=True)
            for t, p in targets.items():
                if force or not p.exists():
                    pq.write_table(built[t], p)
        paths.update({t: str(p.resolve()) for t, p in targets.items()})
    return paths


def local_parquet_datastore_config(
    base_dir: str | os.PathLike | None = None,
) -> dict[str, Any]:
    """``duckdb`` datastore config reading all 17 demo tables from local parquet.

    The config mirrors the S3 variant exactly — ``database=":memory:"`` plus a
    multi-statement ``view_sql`` of ``CREATE VIEW <t> AS SELECT * FROM
    read_parquet('<abs path>')`` — so the normal connector → /query →
    /data-browser pipeline serves it with zero special-casing.  Call
    ``export_demo_parquet_local()`` first so the files exist.
    """
    base = Path(base_dir) if base_dir is not None else LOCAL_PARQUET_DIR

    view_statements: list[str] = []
    for dataset, tables in DATASET_TABLES.items():
        for table in tables:
            path = _parquet_local_path(dataset, table, base).resolve()
            view_statements.append(
                f"CREATE OR REPLACE VIEW {table} AS SELECT * FROM read_parquet('{path}')"
            )

    return {
        "connector_type": "duckdb",
        "database": ":memory:",
        "view_sql": ";\n".join(view_statements),
        "description": (
            "Demo datasets (retail sales, SaaS metrics, web analytics, finance ops) "
            "backed by local parquet files."
        ),
        "demo_local_dir": str(base),
        "sample": True,
        # Internal: backs the demo dashboards/queries by id. The connectors list
        # surfaces the branded virtual "Demo data" connector instead of this raw
        # row, so flag it system so list_connectors hides it (no duplicate card).
        "system": True,
    }




